project:
  type: website
  resources: 
    - "files/**"
  output-dir: docs
  render:
  - index.qmd
  - 404.qmd
  - syllabus.qmd
  - schedule.qmd
  - assessments.qmd
  - assessments/
  - glossary/
  - resources.qmd
  - week11/
  - week12/
  - week13/
  - week14/
  - week15/
  # - week16/
  # - week17/
  # - week18/
  # - week19/
  # - week20/
  - textbook/index.qmd
  - textbook/chapters/w11-lecture.qmd
  - textbook/chapters/w11-lab.qmd
  - textbook/chapters/w12-lecture.qmd
  - textbook/chapters/w12-lab.qmd
  - textbook/chapters/w13-lecture.qmd
  - textbook/chapters/w13-lab.qmd
  - textbook/chapters/w14-lecture.qmd
  - textbook/chapters/w14-lab.qmd
  - textbook/chapters/w15-lecture.qmd
  - textbook/chapters/w15-lab.qmd
  # - textbook/chapters/w16-lecture.qmd
  # - textbook/chapters/w16-lab.qmd
  # - textbook/chapters/w17-lecture.qmd
  # - textbook/chapters/w17-lab.qmd
  # - textbook/chapters/w18-lecture.qmd
  # - textbook/chapters/w18-lab.qmd
  # - textbook/chapters/w19-lecture.qmd
  # - textbook/chapters/w19-lab.qmd
  # - textbook/chapters/w20-lecture.qmd
  # - textbook/chapters/w20-lab.qmd
  - textbook/quizzes/w11-quiz.qmd
  - textbook/quizzes/w12-quiz.qmd
  - textbook/quizzes/w13-quiz.qmd
  - textbook/quizzes/w14-quiz.qmd
  - textbook/quizzes/w15-quiz.qmd
  # - textbook/quizzes/w16-quiz.qmd
  # - textbook/quizzes/w17-quiz.qmd
  # - textbook/quizzes/w18-quiz.qmd
  # - textbook/quizzes/w19-quiz.qmd
  # - textbook/quizzes/w20-quiz.qmd
website:
  title: PS50008A Research Methods & Experimental Design
  description: Term 2 Spring 2026
  site-url: https://littlemonkeylab.github.io/PS50008A_2526/
  repo-url: https://github.com/LittleMonkeyLab/PS50008A_2526
  repo-actions:
  - edit
  - issue
  navbar:
    logo: assets/foundations-26-logo.svg
    left:
    - text: Home
      href: index.qmd
    - text: Syllabus
      href: syllabus.qmd
    - text: Schedule
      href: schedule.qmd
    - text: Assessments
      menu:
      - text: Overview
        href: assessments.qmd
      - text: '---'
      - text: Research Plan
        href: assessments/research-plan.qmd
      - text: MCQ Exam
        href: assessments/mcq-exam.qmd
      - text: EDS Assignment
        href: assessments/eds-assignment.qmd
      - text: Research Report
        href: assessments/research-report.qmd
    - text: Resources
      href: resources.qmd
    - text: Textbook
      href: textbook/index.qmd
    - text: Glossary        
      href: glossary/index.qmd
    right:
    - icon: github
      href: https://github.com/LittleMonkeyLab/PS50008A_2526
  sidebar:
    style: docked
    search: true
    contents:
    - section: Overview
      contents:
      - index.qmd
      - syllabus.qmd
      - schedule.qmd
      - section: Assessments
        contents:
        - text: Overview
          href: assessments.qmd
        - text: Research Plan
          href: assessments/research-plan.qmd
        - text: MCQ Exam
          href: assessments/mcq-exam.qmd
        - text: EDS Assignment
          href: assessments/eds-assignment.qmd
        - text: Research Report
          href: assessments/research-report.qmd
      - resources.qmd
      - text: Glossary           
        href: glossary/index.qmd
    - section: Term 2
      contents:
      - section: 'Week 11: DataLab'
        contents:
        - text: Overview
          href: week11/index.qmd
        - section: Lecture
          contents:
          - text: Reading
            href: week11/lecture/reading.qmd
          - text: Slides
            href: week11/lecture/slides.qmd
            target: _blank
        - section: Lab
          contents:
          - text: Instructor Slides
            href: week11/lab/instructor-slides.qmd
            target: _blank
          - text: Activity
            href: week11/lab/activity.qmd
          - text: Reading
            href: week11/lab/reading.qmd
          - text: Data Dictionary
            href: week11/lab/data-dictionary.qmd
      - section: 'Week 12: Research Design Framework'
        contents:
        - text: Overview
          href: week12/index.qmd
        - section: Lecture
          contents:
          - text: Reading
            href: week12/lecture/reading.qmd
          - text: Slides
            href: week12/lecture/slides.qmd
            target: _blank
        - section: Lab
          contents:
          - text: Instructor Slides
            href: week12/lab/instructor-slides.qmd
            target: _blank
          - text: Activity
            href: week12/lab/activity.qmd
          - text: Reading
            href: week12/lab/reading.qmd
          - text: Self-Assessment
            href: week12/lab/self-assessment.qmd
      - section: 'Week 13: Building your Research (Plan)'
        contents:
        - text: Overview
          href: week13/index.qmd
        - section: Lecture
          contents:
          - text: Reading
            href: week13/lecture/reading.qmd
          - text: Slides
            href: week13/lecture/slides.qmd
            target: _blank
        - section: Lab
          contents:
          - text: Instructor Slides
            href: week13/lab/instructor-slides.qmd
            target: _blank
          - text: Activity
            href: week13/lab/activity.qmd
          - text: Reading
            href: week13/lab/reading.qmd
      - section: 'Week 14: Inference & t-tests'
        contents:
        - text: Overview
          href: week14/index.qmd
        - section: Lecture
          contents:
          - text: Reading
            href: week14/lecture/reading.qmd
          - text: Slides
            href: week14/lecture/slides.qmd
            target: _blank
        - section: Lab
          contents:
          - text: Instructor Slides
            href: week14/lab/instructor-slides.qmd
            target: _blank
          - text: Activity
            href: week14/lab/activity.qmd
          - text: Reading
            href: week14/lab/reading.qmd
      - section: 'Week 15: Correlation'
        contents:
        - text: Overview
          href: week15/index.qmd
        - section: Lecture
          contents:
          - text: Reading
            href: week15/lecture/reading.qmd
          - text: Slides
            href: week15/lecture/slides.qmd
            target: _blank
        - section: Lab
          contents:
          - text: Instructor Slides
            href: week15/lab/instructor-slides.qmd
            target: _blank
          - text: Activity
            href: week15/lab/activity.qmd
          - text: Reading
            href: week15/lab/reading.qmd
      # - section: 'Week 16: Regression'
      #   contents:
      #   - text: Overview
      #     href: week16/index.qmd
      #   - section: Lecture
      #     contents:
      #     - text: Reading
      #       href: week16/lecture/reading.qmd
      #     - text: Slides
      #       href: week16/lecture/slides.qmd
      #       target: _blank
      #   - section: Lab
      #     contents:
      #     - text: Instructor Slides
      #       href: week16/lab/instructor-slides.qmd
      #       target: _blank
      #     - text: Activity
      #       href: week16/lab/activity.qmd
      #     - text: Reading
      #       href: week16/lab/reading.qmd
      # - section: 'Week 17: Interpretation & Credibility'
      #   contents:
      #   - text: Overview
      #     href: week17/index.qmd
      #   - section: Lecture
      #     contents:
      #     - text: Reading
      #       href: week17/lecture/reading.qmd
      #     - text: Slides
      #       href: week17/lecture/slides.qmd
      #       target: _blank
      #   - section: Lab
      #     contents:
      #     - text: Instructor Slides
      #       href: week17/lab/instructor-slides.qmd
      #       target: _blank
      #     - text: Activity
      #       href: week17/lab/activity.qmd
      #     - text: Reading
      #       href: week17/lab/reading.qmd
      # - section: 'Week 18: MCQ Exam'
      #   contents:
      #   - text: Overview
      #     href: week18/index.qmd
      #   - section: Lecture
      #     contents:
      #     - text: Reading
      #       href: week18/lecture/reading.qmd
      #   - section: Lab
      #     contents:
      #     - text: Instructor Slides
      #       href: week18/lab/instructor-slides.qmd
      #       target: _blank
      #     - text: Activity
      #       href: week18/lab/activity.qmd
      #     - text: Reading
      #       href: week18/lab/reading.qmd
      # - section: 'Week 19: Project Workshop'
      #   contents:
      #   - text: Overview
      #     href: week19/index.qmd
      #   - section: Lecture
      #     contents:
      #     - text: Reading
      #       href: week19/lecture/reading.qmd
      #     - text: Slides
      #       href: week19/lecture/slides.qmd
      #       target: _blank
      #   - section: Lab
      #     contents:
      #     - text: Instructor Slides
      #       href: week19/lab/instructor-slides.qmd
      #       target: _blank
      #     - text: Activity
      #       href: week19/lab/activity.qmd
      #     - text: Reading
      #       href: week19/lab/reading.qmd
      # - section: 'Week 20: Wrapping Up'
      #   contents:
      #   - text: Overview
      #     href: week20/index.qmd
      #   - section: Lecture
      #     contents:
      #     - text: Reading
      #       href: week20/lecture/reading.qmd
      #     - text: Slides
      #       href: week20/lecture/slides.qmd
      #       target: _blank
      #   - section: Lab
      #     contents:
      #     - text: Instructor Slides
      #       href: week20/lab/instructor-slides.qmd
      #       target: _blank
      #     - text: Activity
      #       href: week20/lab/activity.qmd
      #     - text: Reading
      #       href: week20/lab/reading.qmd
    - section: Textbook
      contents:
      - text: Overview
        href: textbook/index.qmd
      - section: Week 11
        contents:
        - text: 'Lecture: Introduction to Research'
          href: textbook/chapters/w11-lecture.qmd
        - text: 'Lab: DataLab Foundations'
          href: textbook/chapters/w11-lab.qmd
      - section: Week 12
        contents:
        - text: 'Lecture: Research Design Framework'
          href: textbook/chapters/w12-lecture.qmd
        - text: 'Lab: Design Detectives'
          href: textbook/chapters/w12-lab.qmd
      - section: Week 13
        contents:
        - text: 'Lecture: Design Decisions'
          href: textbook/chapters/w13-lecture.qmd
        - text: 'Lab: Research Plan Work'
          href: textbook/chapters/w13-lab.qmd
      - section: Week 14
        contents:
        - text: 'Lecture: Inference & t-tests'
          href: textbook/chapters/w14-lecture.qmd
        - text: 'Lab: t-tests in R'
          href: textbook/chapters/w14-lab.qmd
      - section: Week 15
        contents:
        - text: 'Lecture: Correlation'
          href: textbook/chapters/w15-lecture.qmd
        - text: 'Lab: Correlation in R'
          href: textbook/chapters/w15-lab.qmd
      # - section: Week 16
      #   contents:
      #   - text: 'Lecture: Regression'
      #     href: textbook/chapters/w16-lecture.qmd
      #   - text: 'Lab: Project Groups'
      #     href: textbook/chapters/w16-lab.qmd
      # - section: Week 17
      #   contents:
      #   - text: 'Lecture: Interpretation & Credibility'
      #     href: textbook/chapters/w17-lecture.qmd
      #   - text: 'Lab: Project Groups'
      #     href: textbook/chapters/w17-lab.qmd
      # - section: Week 18
      #   contents:
      #   - text: 'Lecture: MCQ Exam Prep'
      #     href: textbook/chapters/w18-lecture.qmd
      #   - text: 'Lab: Project Groups'
      #     href: textbook/chapters/w18-lab.qmd
      # - section: Week 19
      #   contents:
      #   - text: 'Lecture: Project Workshop'
      #     href: textbook/chapters/w19-lecture.qmd
      #   - text: 'Lab: Data Collection'
      #     href: textbook/chapters/w19-lab.qmd
      # - section: Week 20
      #   contents:
      #   - text: 'Lecture: Wrapping Up'
      #     href: textbook/chapters/w20-lecture.qmd
      #   - text: 'Lab: Report Writing'
      #     href: textbook/chapters/w20-lab.qmd
      - section: Self-Assessment Quizzes
        contents:
        - text: Week 11 Quiz
          href: textbook/quizzes/w11-quiz.qmd
        - text: Week 12 Quiz
          href: textbook/quizzes/w12-quiz.qmd
        - text: Week 13 Quiz
          href: textbook/quizzes/w13-quiz.qmd
        - text: Week 14 Quiz
          href: textbook/quizzes/w14-quiz.qmd
        - text: Week 15 Quiz
          href: textbook/quizzes/w15-quiz.qmd
        # - text: Week 16 Quiz
        #   href: textbook/quizzes/w16-quiz.qmd
        # - text: Week 17 Quiz
        #   href: textbook/quizzes/w17-quiz.qmd
        # - text: Week 18 Quiz
        #   href: textbook/quizzes/w18-quiz.qmd
        # - text: Week 19 Quiz
        #   href: textbook/quizzes/w19-quiz.qmd
        # - text: Week 20 Quiz
        #   href: textbook/quizzes/w20-quiz.qmd
  page-footer:
    left: PS50008A Research Methods & Experimental Design | Goldsmiths, University
      of London
    right: Term 2 Spring 2026
format:
  html:
    theme: cosmo
    css:
    - assets/custom.css
    - include/webex.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    link-external-newwindow: true
    comments:
      hypothesis: true
    include-after-body: include/webex.js
date-format: D MMMM YYYY
execute:
  freeze: auto

